".vim -> dotfiles/vim
set nocompatible              " be iMproved, required
filetype off                  " required

" ================ General Config ====================
"
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set cursorline

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" =============== Plug Initialization ===============
" " This loads all the plugins specified in ~/.vim/plug.vim
" " Use plug plugin to manage all other plugins
if filereadable(expand("~/.vim/plug.vim"))
  source ~/.vim/plug.vim
endif

" ================ Turn Off Swap Files ==============
"
set noswapfile
set nobackup
set nowb

" ================ Indentation ======================
"
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=4
set expandtab

filetype plugin on
filetype indent on

set tags=./tags;,tags;


" Display tabs and trailing spaces visually
" set list listchars=tab:\ \ ,trail:·
"
set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points

" Use spacebar for folding.
nnoremap <space> za
vnoremap <space> zf

" Use ; for commands.
nnoremap ; :

" Rotate between last two files
nnoremap ,n <C-^>
nnoremap ,gb <C-O>

" ================ Scrolling ========================
"
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

nnoremap <silent> \t :NERDTreeToggle<CR>

" search for visually hightlighted text
vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>


let python_highlight_all=1
syntax enable
syntax on

so ~/.vim/settings.vim

" set background=dark
" colorscheme hybrid
" let g:solarized_termcolors=256
colorscheme molokai
let g:molokai_original = 1
set clipboard=unnamed

autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
autocmd Filetype python setlocal ts=4 sts=4 sw=4


set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.class,*/target/*,*/node_modules/*,*/bower_components/*
set wildignore+=*/dist/*

set re=1
noremap <F4> :set hlsearch! hlsearch?<CR>

" Ack
let g:ackprg = 'ag --vimgrep --smart-case'
cnoreabbrev ag Ack
cnoreabbrev aG Ack
cnoreabbrev Ag Ack
cnoreabbrev AG Ack

"let g:EclimCompletionMethod = 'omnifunc'
"
"if !exists('g:neocomplcache_force_omni_patterns')
"    let g:neocomplcache_force_omni_patterns = {}
"endif
"let g:neocomplcache_force_omni_patterns.java = '\k\.\k*'
"let g:neocomplcache_force_omni_patterns.scala = '\k\.\k*'
"
:command! CurrentPath let @+ = expand('%:p')
